FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1
ENV FLASK_ENV=production
ENV FLASK_APP=external_api.py

EXPOSE 5001

CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]